model:
  model_class: BaselineTest6
  model_setting:
    dim: 512
    n_heads: 8
    dim_ff: 2048
    pred_drop: 0.0
    vocab_size: 700
    loss_type: MapeLoss
    # loss_type: RootMapeLoss
    num_basic_block_layer: 0
    num_instruction_layer: 1
    num_op_layer: 0
    pad_idx: from:data.special_token_idx.PAD
    use_checkpoint: false
train:
  seed: 3431
  batch_size: 16
  val_batch_size: 16
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
    # weight_decay: 0.0001
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  hyperparameter_testing:
    using: False
    mult: 0.2



data:
  data_file: training_data/spec_core_0714.data
  # src_info_file: training_data/skl_mapping.csv
  data_setting:
    bert: false
    only_unique: true
    split_mode: none
    train_perc: 8
    val_perc: 2
    test_perc: 0
    prepare_mode: stacked_raw
    shuffle: false
    instr_limit: 1
    custom_idx_split: saved/SR:B_splited_evenly/0901/idx_dict.dump
  dataset_class: StackedBlockDataset
  dataset_setting:
    too_long_limit: 512
  # raw_data: false
  #  sample usage of predifined special token idxs
  special_token_idx:
    PAD: 0
    BLOCK_START: 1
    BLOCK_END: 2
    START: 3
    END: 4  
    SEP: 5
    UNK: 6 
    MSK: 7
    # PAD: 0
    # SRCS: 1
    # DSTS: 2
    # MEM: 3 # <MEM>
    # /MEM: 4  # </MEM>
    # START: 5
    # END: 6
    # UNK: 7 
    # OP: 8
    # BASE: 9
    # INDEX: 10
    # DISP: 11
    # SCALE: 12

    