model:
  model_class: BertMixedOnly
  model_setting:
    n_heads: 12
    pred_drop: 0.1
    loss_type: MapeLoss
    pad_idx: from:data.special_token_idx.PAD
    pretrained: from:pretrained.model
train:
  is_bert: false
  seed: 3431
  batch_size: 32
  val_batch_size: 32
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
    # weight_decay: 0.01
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  hyperparameter_testing:
    using: False
    mult: 0.2
pretrained:
  # saved_path: saved/bp2L_12_layer_hard/0829
  saved_path: saved/bp2L_easy_12_layer/0829
  using_model_file: trained.mdl
  model: set_from_code
