model:
  model_class: BertBaseline
  model_setting:
    dim: 512
    n_heads: 8
    dim_ff: 2048
    pred_drop: 0.1
    vocab_size: 660
    num_basic_block_layer: 2
    num_instruction_layer: 2
    num_op_layer: 4
    pad_idx: from:data.special_token_idx.PAD
    end_idx: from:data.special_token_idx.END
    bert_weight: model_resources/bert/bert_weights.pth
train:
  seed: 3431
  batch_size: 16
  val_batch_size: 16
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  gradient_accumlation:
    using: false
    steps: 4
  loss: MapeLoss
  # loss_setting:
  save_epoch: -1
    # x == 0: no save
    # x == -1: just save best and last epoch
    # x > 0: save every `x`th epoch and also best and last
  cpu_count: null
    # x == null: use multiprocessing.cpu_count
    # x == number: use that value
data:
  data_file: training_data/intel_core.data
  data_setting:
    only_unique: true
    split_mode: num_instrs
    train_perc: 8
    val_perc: 2
    test_perc: 0
    prepare_mode: stacked
    shuffle: true
    instr_limit: 400
    custom_idx_split: model_resources/data/idx_dict.dump
    given_token_mapping: model_resources/bert/token_mapping.dump
  dataset_class: BERTNoMaskDataset
  dataset_setting:
    too_long_limit: 512
