model:
  model_class: PadZeroCheckpoint
  model_setting:
    use_checkpoint: true
    dim: 768
    n_heads: 12
    dim_ff: 3072
    pred_drop: 0.1
    vocab_size: 700
    loss_type: MapeLoss
    num_basic_block_layer: 2
    num_instruction_layer: 2
    num_op_layer: 4
    checkpoint_cnt: 1
    pad_idx: from:data.special_token_idx.PAD

train:
  seed: 3431
  batch_size: 8
  val_batch_size: 8
  n_epochs: 30
  warmup: 0.001
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  hyperparameter_testing:
    using: False
    mult: 0.2

data:
  data_file: training_data/spec_core_0714.data
  # src_info_file: training_data/skl_mapping.csv
  data_setting:
    bert: false
    only_unique: true
    split_mode: none
    train_perc: 8
    val_perc: 2
    test_perc: 0
    prepare_mode: stacked_extra_tags
    shuffle: false
    only_one: false
  dataset_class: StackedBlockDataset
  dataset_setting:
    too_long_limit: 512
  # raw_data: false
  #  sample usage of predifined special token idxs
  special_token_idx:
    PAD: 0
    SRCS: 1
    DSTS: 2
    MEM: 3 # <MEM>
    MEM_FIN: 4  # </MEM>
    END: 5
    UNK: 6 
