model:
  model_class: DeepPMLearnableWeight
  model_setting:
    dim: 512
    n_heads: 8
    dim_ff: 2048
    vocab_size: 700
    num_basic_block_layer: 2
    num_instruction_layer: 2
    num_op_layer: 4
    pad_idx: from:data.special_token_idx.PAD
    use_checkpoint: true
    dist_weight_len_limit: 40
train:
  seed: 3431
  batch_size: 16
  val_batch_size: 16
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  gradient_accumlation:
    using: False
    steps: 4
  loss: MapeLoss
  # loss_setting:
data:
  data_file: training_data/intel_core.data
  data_setting:
    only_unique: true
    split_mode: num_instrs
    train_perc: 8
    val_perc: 2
    test_perc: 0
    prepare_mode: stacked_raw
    shuffle: true
    instr_limit: 400
    custom_idx_split: model_resources/data/idx_dict.dump
    given_token_mapping: model_resources/data/data_mapping.dump
    # given_token_mapping: null
  dataset_class: DatasetWithDistanceWeight
  dataset_setting:
    return_raw_dist_weight: true
    dist_weight_len_limit: 40
    too_long_limit: 512
  special_token_idx:
    PAD: 0
    BLOCK_START: 1
    BLOCK_END: 2
    START: 3
    END: 4  
    SEP: 5
    UNK: 6 
    MSK: 7