model:
  model_class: JustLinear
  model_setting:
    dim: 768
    pred_drop: 0.1
    vocab_size: -1
    loss_type: MapeLoss
    pad_idx: from:data.special_token_idx.PAD
train:
  is_bert: false
  seed: 3431
  batch_size: 32
  val_batch_size: 32
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
    # weight_decay: 0.01
  lr_scheduler: LinearLR
  use_batch_step_lr: false
  lr_scheduler_setting:
    total_iters: 5
  hyperparameter_testing:
    using: False
    mult: 0.2
data:
  data_file: training_data/spec_core_0714.data
  # src_info_file: training_data/skl_mapping.csv
  data_setting:
    bert: false
    only_unique: true
    split_mode: short_in_train:199
    train_perc: 8
    val_perc: 2
    test_perc: 0
    prepare_mode: stacked_extra_tags
    shuffle: false
    # instr_limit: 400
    instr_limit: 2
  dataset_class: StackedBlockDataset
  dataset_setting:
    too_long_limit: 512
  # raw_data: false
  #  sample usage of predifined special token idxs
  special_token_idx:
    PAD: 0
    SRCS: 1
    DSTS: 2
    MEM: 3 # <MEM>
    /MEM: 4  # </MEM>
    START: 5
    END: 6
    UNK: 7 
    OP: 8
    BASE: 9
    INDEX: 10
    DISP: 11
    SCALE: 12

    