model:
  model_class: MaskedLang
  model_setting:
    dim: 512
    n_heads: 8
    dim_ff: 2048
    pred_drop: 0.0
    vocab_size: 250
    loss_type: MapeLoss
    num_basic_block_layer: 2
    num_instruction_layer: 2
    num_op_layer: 4
    block_activation: gelu
    pad_idx: from:data.special_token_idx.PAD
    unk_idx: from:data.special_token_idx.UNK

train:
  seed: 3431
  batch_size: 16
  val_batch_size: 16
  n_epochs: 30
  clip_grad_norm: 0.2
  optimizer: Adam
  optimizer_setting:
    lr: 0.00001
    weight_decay: 0.01
  use_batch_step_lr: true
  lr_scheduler: get_warmp_with_decay_lr_sched
  lr_scheduler_setting:
    warmup_ratio: 0.1
  hyperparameter_testing:
    using: False
    mult: 0.2

data:
  data_file: training_data/intel_core.data
  # src_info_file: training_data/skl_mapping.csv
  data_setting:
    bert: true
    only_unique: true
    stacked: true
    split_mode: num_instrs
    train_perc: 8
    val_perc: 2
    test_perc: 0
  dataset_class: StackedBlockDataset
  dataset_setting:
    too_long_limit: 512
  # raw_data: false
  #  sample usage of predifined special token idxs
  special_token_idx:
    PAD: 0
    START: 1
    END: 2
    INS_START: 3
    INS_END: 4
    OP: 5
    SRCS: 6
    DSTS: 7
    MEM: 8 # <MEM>
    MEM_FIN: 9  # </MEM>
    UNK: 10
